name: Validate code

on:
  - push

jobs:
  test:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set-up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Create cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Run lint
        run: flake8 unaflow

      - name: Make package
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*