name: Create release distribution

on:
  release:
    types: [created]

jobs:
  upload-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create dist
        id: create_dist
        run: |
          make package
          echo "##[set-output name=path;]$(ls dist/unaflow*.zip)"
          echo "##[set-output name=basename;]$(basename dist/unaflow*.zip)"

      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.create_dist.outputs.path }}
          asset_name: ${{ steps.create_dist.outputs.basename }}
          asset_content_type: application/gzip
