name: Create draft release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  upload-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set-up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Create cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Make package
        run: |
          python3 setup.py sdist bdist_wheel
          twine check dist/*

      - name: Upload to test.pypi.org
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*