name: Release to PyPi

on:
  release:
    types: [published]

jobs:
  upload-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create dist
        id: create_dist
        run: make package

      - name: Upload to pypi.org
        if:
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        with:
          twine upload  dist/*
