name: Create draft release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  upload-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create dist
        id: create_dist
        run: make package

      - name: Upload to test.pypi.org
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*